config/routes.rb
Rails.application.routes.draw do


root to:'gossip#index'

get '/team', to: 'static#presentation'

get '/contact', to: 'static#contact'

get '/gossip/:id', to: 'gossip#show', as: 'gossip'

get '/user/:id', to: 'user#show', as: 'user'

get '/welcome/first_name', to: 'static#welcome', as: 'welcome'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags, dependent: :destroy
  has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags, dependent: :destroy
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def index
    @gossips = Gossip.all
  end 
  
  def show 
    @gossip = Gossip.find(params[:id])
  end 

end 

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def presentation
  end 

  def home 
  end 

  def contact
  end 

  def welcome
  
  end
end 

app/controllers/user_controller.rb
class UserController < ApplicationController

def show
  @user = User.find(params[:id])
end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gossip/index.html.erb
<div class="container">
  <h1 class="text-center mt-4"> Welcome on The Gossip Project </h1>
  <h2 class="text-center">Découvrez tous les derniers potin de la fameuse formation de THP</h2>

  <div class="row justify-content-center">
  <% @gossips.each do |gossip| %>
  <div class="card p-0 m-4 col-sm-12 col-md-4 col-lg-3">
    <div class="card-body">
      <h5 class="card-title"><%=gossip.title%></h5>
      <p class="card-text"><%= truncate(gossip.content, length: 50) %></p>
      <%= link_to "Lire le gossip", gossip_path(gossip.id) %>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= link_to "Ecrit par #{gossip.user.first_name}, le #{gossip.created_at.strftime("%d/%m/%Y")}" , user_path(gossip.user.id) %></small>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to 'The Gossip Project', root_path, class: "nav-link" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'Team', team_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<div class="container">
  <h1 class="text-center mt-4"> Profil de <%= @user.first_name %> <%= @user.last_name%> </h1>

  <p> Description :<%= @user.description%> </p>
  <p> Email : <%= @user.email%> </p>
  <p> Age : <%= @user.age%> </p>
  <p> Ville: <%= @user.city.name%> </p>

  <h2 class="mb-2 mt-4">Tous mes gossips</h2>
  <div class="row justify-content-center">
    <% @user.gossips.each do |gossip| %>
      <div class="card m-4 p-0 mt-4 col-sm-12 col-md-4 col-lg-3">
        <div class="card-body">
          <h5 class="card-title"><%=gossip.title%></h5>
          <p class="card-text"><%= truncate(gossip.content, length: 50) %></p>
          <%= link_to "Lire le gossip", gossip_path(gossip.id) %>
        </div>
        <div class="card-footer">
          <small class="text-muted"><%= link_to "Ecrit par #{gossip.user.first_name}, le #{gossip.created_at.strftime("%d/%m/%Y")}" , user_path(gossip.user.id) %></small>
        </div>
      </div>
    <% end %>
  </div>
</div